---
# Confidential configuration:
# 
# - Decryption filter with access profile that allows
#   keyset usage for decrypting confidential fields.
#   Client apps routed/forced through this proxy instance
#   can see all payload fields up to confidential level,
#   but nothing that would require higher clearance.
management:
  endpoints:
    prometheus: {}

virtualClusters:
  - name: demo-cluster
    targetCluster:
      bootstrapServers: kafka:9092
    gateways:
      - name: demo-gateway
        portIdentifiesNode:
          bootstrapAddress: kroxylicious-confidential:9192
    logNetwork: false
    logFrames: false

filterDefinitions:
  - name: k4k-decrypt-confidential
    type: com.github.hpgrahsl.kroxylicious.filters.kryptonite.filter.KryptoniteDecryptionFilterFactory
    config:
      key_source: CONFIG
      cipher_algorithm: TINK/AES_GCM
      cipher_data_key_identifier: keyA
      # This proxy instance and filter config 
      # only has access to the necessary subset
      # of the cryptographic keys, here keyB. In practice,
      # this would be achieved by centrally managed
      # keysets in a KMS together with proper permissions.
      cipher_data_keys:
        - identifier: keyB
          material:
            primaryKeyId: 1001
            key:
              - keyData:
                  typeUrl: type.googleapis.com/google.crypto.tink.AesGcmKey
                  value: GiBIZWxsbyFXb3JsZEZVQ0sxYWJjZGprbCQxMjM0NTY3OA==
                  keyMaterialType: SYMMETRIC
                status: ENABLED
                keyId: 1001
                outputPrefixType: TINK
      record_format: JSON_SR
      schema_registry_url: http://schema-registry:8081
      schema_mode: DYNAMIC
      topic_field_configs:
        - topic_pattern: demo-kroxy-k4k.*
          field_configs:
            # Can only ever decrypt fields
            # for which the security clearance
            # of this proxy instance allows access
            # to the required keysets, here keyB.
            - name: knownresidences
              fieldMode: OBJECT
              keyId: keyB

defaultFilters:
  - k4k-decrypt-confidential
